.PHONY: sync fetch-kubectl check check-cairn-mcp check-a2a test test-backup test-restore contract render compose-config \
	image smoke-image kind-acceptance pre-blind compose-acceptance reference-acceptance \
	reference-posture-acceptance reference-posture-launch

IMAGE ?= cairn:dev
KUBECTL = build/tools/kubectl
IMAGES_LOCK = deploy/images.lock
RENDER_DIR = deploy/kustomize/rendered
COMPOSE_DIR = deploy/compose
CAIRN_MCP_DIR = cairn-mcp
A2A_DIR = a2a
# P-69: the pins reach Compose from $(IMAGES_LOCK) itself, and the
# instance parameters from the committed example. Both compositions are
# validated — with and without the retrieval overlay — because an overlay
# that no longer composes is exactly as broken as a base that does not.
COMPOSE = docker compose --env-file $(IMAGES_LOCK) \
	--env-file $(COMPOSE_DIR)/.env.example -f $(COMPOSE_DIR)/compose.yaml
# One entry per applyable configuration, as `name:source`. The name is
# what the render is committed as, so adding a configuration is one line
# here and the gate covers it from that moment.
RENDERS = \
	base:deploy/kustomize/base \
	kind:deploy/kustomize/overlays/kind \
	kubernetes:deploy/kustomize/overlays/kubernetes \
	kubernetes-retrieval:deploy/kustomize/overlays/kubernetes-retrieval \
	openshift:deploy/kustomize/overlays/openshift \
	egress-gateway:deploy/kustomize/overlays/egress-gateway \
	egress-gateway-reference:deploy/kustomize/overlays/egress-gateway-reference
REVISION ?= $(shell git rev-parse HEAD 2>/dev/null || printf unknown)
ifneq ($(filter /mnt/%,$(CURDIR)),)
$(error Cairn must run from a native Linux filesystem; checkout is under $(CURDIR))
endif
TMPDIR := /tmp
AUDIT_DIR ?= build/audit
AUDIT_LOCK ?= $(AUDIT_DIR)/pylock.cairn.toml
CONTRACT = contracts/cairn-openapi-v1.json
PACKAGED_CONTRACT = src/cairn/contracts/cairn-openapi-v1.json
CONTRACT_TMP = $(CONTRACT).tmp
MANIFEST = contracts/cairn-mcp-tools-v1.json
PACKAGED_MANIFEST = src/cairn/contracts/cairn-mcp-tools-v1.json
MANIFEST_TMP = $(MANIFEST).tmp
MEMORY_CONTRACT = contracts/cairn-memory-openapi-v1.json
MEMORY_MANIFEST = contracts/cairn-memory-mcp-tools-v1.json
MEMORY_PACKAGED = src/cairn/contracts

export TMPDIR

sync:
	uv sync --locked

# Keep the client binary out of the repository and fetch it only when a target
# needs it. The helper verifies the lock-file checksum before installing it.
fetch-kubectl:
	./scripts/fetch-kubectl

# tests/conformance is named explicitly so the xdist controller pre-loads
# its conftest: under -n auto workers do the collecting, and without the
# arg the controller never registers the report emitter's hooks — worker
# outcomes then have nowhere to land and no conformance report is
# written. Listing the directory twice is safe: pytest drops duplicate
# collection by default.
test:
	uv run --locked pytest -n auto tests/conformance tests

test-backup:
	uv run --locked pytest tests/runtime/test_backup_cli.py \
		-o addopts="--strict-config --strict-markers --cov=cairn.operations.backup \
		--cov-branch --cov-report=term-missing --cov-fail-under=100"

test-restore:
	uv run --locked pytest tests/runtime/test_restore_cli.py \
		-o addopts="--strict-config --strict-markers --cov=cairn.operations.restore \
		--cov-branch --cov-report=term-missing --cov-fail-under=100"

check-cairn-mcp:
	cd $(CAIRN_MCP_DIR) && go vet ./...
	cd $(CAIRN_MCP_DIR) && go test ./...
	cd $(CAIRN_MCP_DIR) && go test -race ./...

# The Garden component ships with the distribution, so its Go suite, offline
# installer tests and build-version check gate the repository like cairn-mcp.
# Blind acceptance found `a2a --version` reporting `dev` while this suite
# was only run by hand.
check-a2a:
	$(MAKE) -C $(A2A_DIR) check

# P-30: both copies of each artefact and its digest come from one render.
# The generator writes to stdout and this target owns the paths. The
# temporary file is not ceremony: redirection truncates its target before
# the command runs, so rendering straight to $(CONTRACT) would empty the
# committed artefact whenever generation failed. It sits beside its
# destination rather than under $(TMPDIR) so the rename stays on one
# filesystem and is therefore atomic; a leftover .tmp is untracked and
# invisible to the gate below.
#
# P-58: the I-89 MCP manifest is generated by the identical five lines,
# because it is the same kind of artefact under the same determinism
# rules. Two targets would let one be regenerated without the other.
contract:
	uv run --locked python -m cairn.transports.rest.v1.openapi > $(CONTRACT_TMP)
	mv $(CONTRACT_TMP) $(CONTRACT)
	cp $(CONTRACT) $(PACKAGED_CONTRACT)
	cd $(dir $(CONTRACT)) && sha256sum $(notdir $(CONTRACT)) > $(notdir $(CONTRACT)).sha256
	uv run --locked python -m cairn.transports.mcp.manifest > $(MANIFEST_TMP)
	mv $(MANIFEST_TMP) $(MANIFEST)
	cp $(MANIFEST) $(PACKAGED_MANIFEST)
	cd $(dir $(MANIFEST)) && sha256sum $(notdir $(MANIFEST)) > $(notdir $(MANIFEST)).sha256
	uv run --locked python -m cairn.transports.memory.contracts > $(MEMORY_CONTRACT).tmp
	mv $(MEMORY_CONTRACT).tmp $(MEMORY_CONTRACT)
	cp $(MEMORY_CONTRACT) $(MEMORY_PACKAGED)/
	cd contracts && sha256sum $(notdir $(MEMORY_CONTRACT)) > $(notdir $(MEMORY_CONTRACT)).sha256
	uv run --locked python -m cairn.transports.memory.contracts --mcp > $(MEMORY_MANIFEST).tmp
	mv $(MEMORY_MANIFEST).tmp $(MEMORY_MANIFEST)
	cp $(MEMORY_MANIFEST) $(MEMORY_PACKAGED)/
	cd contracts && sha256sum $(notdir $(MEMORY_MANIFEST)) > $(notdir $(MEMORY_MANIFEST)).sha256

# P-61: every overlay render is committed with a digest beside it, and
# regenerating it is this target. The same shape as `contract` above and
# for the same reason — one render writes both the artefact and its
# digest, and the temporary file exists because redirection truncates its
# target before the command runs.
#
# The renderer is the pinned kubectl and nothing else, so what renders the
# artefacts is the same binary that applies them. `fetch-kubectl` obtains it
# on demand and verifies its checksum before this client-side render starts.
render: fetch-kubectl
	@locked=$$(awk -F= '$$1 == "KUBECTL_VERSION" {print $$2}' $(IMAGES_LOCK)); \
	client=$$($(KUBECTL) version --client --output=json | \
		sed -n 's/.*"gitVersion": *"\([^"]*\)".*/\1/p' | head -n 1); \
	if [ "$$client" != "$$locked" ]; then \
		printf 'kubectl %s is not the pinned %s: run ./scripts/fetch-kubectl\n' \
			"$$client" "$$locked" >&2; \
		exit 1; \
	fi
	@for render in $(RENDERS); do \
		name=$${render%%:*}; source=$${render#*:}; \
		printf 'rendering %s from %s\n' "$$name" "$$source"; \
		$(KUBECTL) kustomize "$$source" > $(RENDER_DIR)/$$name.yaml.tmp || exit 1; \
		mv $(RENDER_DIR)/$$name.yaml.tmp $(RENDER_DIR)/$$name.yaml; \
		( cd $(RENDER_DIR) && sha256sum $$name.yaml > $$name.yaml.sha256 ); \
	done
	./scripts/check-image-pins

# P-69: `docker compose config` parses, interpolates and validates the
# project, so a broken artefact fails here rather than at an operator's
# first `up`. It is client-side and contacts no daemon — which is why it
# belongs in the host gate beside the renders rather than in the image
# job.
#
# FALKORDB_CONFIG_FILE is supplied here and only here. The committed
# example sets no value, because an unset one refuses the composition and
# that refusal is the point; the gate has to satisfy it with a path. The
# path names no file and none is needed — `config -q` interpolates,
# validates and prints nothing, resolving bind sources without ever
# opening one.
compose-config:
	@if ! docker compose version >/dev/null 2>&1; then \
		printf 'the docker compose plugin is missing: the P-69 gate needs it\n' >&2; \
		exit 1; \
	fi
	$(COMPOSE) config -q
	FALKORDB_CONFIG_FILE=./falkordb.conf \
		$(COMPOSE) -f $(COMPOSE_DIR)/compose.graphiti.yaml config -q

check: check-cairn-mcp check-a2a
	uv lock --check
	./scripts/check-license
	uv run --locked ruff check .
	uv run --locked ruff format --check .
	uv run --locked mypy src tests
	$(MAKE) contract
	git diff --exit-code -- $(CONTRACT) $(CONTRACT).sha256 $(PACKAGED_CONTRACT) \
		$(MANIFEST) $(MANIFEST).sha256 $(PACKAGED_MANIFEST) \
		$(MEMORY_CONTRACT) $(MEMORY_CONTRACT).sha256 $(MEMORY_MANIFEST) $(MEMORY_MANIFEST).sha256 \
		$(MEMORY_PACKAGED)/$(notdir $(MEMORY_CONTRACT)) $(MEMORY_PACKAGED)/$(notdir $(MEMORY_MANIFEST))
	$(MAKE) render
	git diff --exit-code -- deploy/kustomize/rendered
	$(MAKE) compose-config
	uv run --locked pytest -n auto tests/conformance tests
	mkdir -p $(AUDIT_DIR)
	uv export --quiet --locked --all-groups --no-emit-project \
		--format pylock.toml --output-file $(AUDIT_LOCK)
	uv run --locked pip-audit --locked $(AUDIT_DIR)

image:
	docker build --pull=false \
		--build-arg REVISION="$(REVISION)" \
		--tag $(IMAGE) .

smoke-image:
	IMAGE=$(IMAGE) ./scripts/smoke-image

# P-68: the disposable acceptance tier. An evidence run on demand and
# never part of `check` — it creates a cluster, pulls pinned images and
# takes minutes, none of which belongs in a host gate.
kind-acceptance:
	IMAGE=$(IMAGE) ./scripts/kind-acceptance

# The blind-acceptance rehearsal: every guided installer mode and feature on
# a real host, driven through the documented procedures and the blind
# tester's own independent checks. On demand, never part of `check`; run it
# on the reference host before handing a release to a blind tester.
pre-blind:
	./scripts/pre-blind

# P-69's production-target evidence tier. Like kind acceptance, this is
# deliberately on demand: it builds images and creates disposable Docker
# projects, networks and volumes on the host named by I-95.
compose-acceptance:
	./scripts/compose-acceptance

# P-70's target-sensitive evidence tier. This must be invoked on reference;
# the script refuses any other host before creating Kubernetes resources.
reference-acceptance:
	./scripts/reference-acceptance

# Task 11a's isolated production-posture tier. Preflight remains a separate,
# explicit invocation; neither target is part of the local gate.
reference-posture-acceptance:
	./scripts/reference-posture-acceptance run

reference-posture-launch:
	./scripts/reference-posture-launch
