"""Deterministic generation of the MCP tool-schema manifest (I-89, P-58),
and the read side of the packaged artefact.

This is the OpenAPI artefact's counterpart for the second transport, and
it is deliberately its clause-for-clause twin: the same render function
shape, the same ``indent=2, sort_keys=True, ensure_ascii=False`` plus a
trailing newline, the same two committed copies, the same ``.sha256``
beside them, and the same ``make check`` dirty-diff gate. A caller that
knows how to pin one knows how to pin the other.

The document carries exactly what I-89 licenses and nothing else: the
eleven I-84 tools with their input and output schemas, the closed
failure-code enumeration, and the protocol revision. Every part is read
from something already load-bearing — ``TOOLS`` is the registry the
server advertises, ``FailureCode`` is the enumeration the failure body
publishes, and the revision is the pinned SDK's own constant — so the
manifest cannot describe a surface the adapter does not serve. It has no
content of its own to drift.

The keys are camelCase because the tool objects' own keys are: they are
the SDK's wire spellings, dumped by alias, and a document that spelled
its envelope one way and its contents another would be a nuisance to
read for no gain.
"""

import json
import sys
from importlib import resources
from typing import Any

from mcp.types import LATEST_PROTOCOL_VERSION, Tool

from cairn.catalogue.transactions import FailureCode
from cairn.transports.mcp.server import TOOLS

# The manifest's path inside the installed package, in the same directory
# and by the same reasoning as the OpenAPI artefact's: the repository copy
# is generated by the same ``make contract`` run, and this is the one an
# instance reads, because a container has no repository.
PACKAGED_ARTEFACT = "contracts/cairn-mcp-tools-v1.json"


def render_document() -> str:
    """The artefact's exact text. Two calls return identical bytes, in
    this process or any other."""
    return json.dumps(_document(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def packaged_manifest_bytes() -> bytes:
    """The manifest as it ships in the wheel. Raises if the package is
    built without it, which is a broken build rather than a runtime
    condition — ``build_application`` refuses to start on it, exactly as
    it does for the OpenAPI artefact."""
    return resources.files("cairn").joinpath(PACKAGED_ARTEFACT).read_bytes()


def _document() -> dict[str, object]:
    return {
        # P-49's ``2025-11-25``, read from the SDK rather than transcribed
        # so that changing the pin changes the artefact and the gate says
        # so. It is the newest revision this build implements, which is
        # what negotiation settles on with any client that asks for the
        # newest or for one this build does not support; a client asking
        # for an older supported revision is answered with that one
        # instead (``mcp/server/session.py``'s ``InitializeRequest``
        # arm), which is a property of the handshake and not of the
        # surface this document describes.
        "protocolVersion": LATEST_PROTOCOL_VERSION,
        "tools": [_tool(tool) for tool in TOOLS],
        # Declaration order, not sorted: this is the identical list the
        # OpenAPI artefact publishes as the failure body's ``code``
        # enumeration, and a test holds the two documents to it.
        "failureCodes": [code.value for code in FailureCode],
    }


def _tool(tool: Tool) -> dict[str, Any]:
    """One advertised tool, in the shape ``tools/list`` returns it.

    ``by_alias`` and ``exclude_none`` are the SDK's own serialisation
    settings for an outgoing frame, so what the manifest publishes is
    what a caller receives rather than a second rendering of it. The
    exclusion is what keeps the document to I-89's four fields: the
    registry sets no title, icons, annotations, ``_meta`` or execution
    hints, and an unset optional has no business appearing as a null.
    """
    return tool.model_dump(mode="json", by_alias=True, exclude_none=True)


if __name__ == "__main__":
    # Bytes, not text: the artefact is UTF-8 regardless of the locale the
    # generator happens to run under.
    sys.stdout.buffer.write(render_document().encode("utf-8"))
