# This context is only for the independent Go Garden image.
*
!Dockerfile
!LICENSE
!THIRD_PARTY_NOTICES.md
!THIRD_PARTY_LICENSES/
!THIRD_PARTY_LICENSES/**
!go.mod
!go.sum
!main.go
!cmd/
!cmd/**
!internal/
!internal/**
